baseurl = "https://blissful-fermat-770c7e.netlify.com"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = 5
preserveTaxonomyNames = true
theme = "nederburg"
title = "Checkout at 11"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "about/"
weight = 2
[[menu.main]]
name = "Get in touch"
url = "contact/"
weight = 3
[params]
author = "Göran Svensson"
authorlink = "https://appernetic.io/"
bio = ["Göran is an avid blogger and the founder of <a href='https://appernetic.io/'>Appernetic.io</a>. This is the author bio shown after posts."]
copyright = ["&copy; 2018 Göran Svensson", "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).", "A port of Tracks by Compete Themes."]
description = "Describe your website"
email = "goran@molnsys.com"
slogan = "A fast &amp; secure theme"
[params.social]
email = "Estillman13@gmail.com"
facebook = ""
github = ""
googleplus = ""
instagram = ""
linkedin = ""
pinterest = ""
rss = false
stackoverflow = ""
twitter = "@EliStillman13"
