baseurl = "https://blissful-fermat-770c7e.netlify.com"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = 5
preserveTaxonomyNames = true
theme = "nederburg"
title = "Checkout at 11"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "about/"
weight = 2
[[menu.main]]
name = "Get in touch"
url = "contact/"
weight = 3
[params]
author = "Eli Stillman"
authorlink = "https://elistillman.com"
bio = ["Eli Stillman fhcfh h f"]
copyright = ["&copy; 2018 Eli Stillman"]
description = "Describe your website"
email = "Estillman13@gmail.com"
slogan = "Passing Through"
[params.social]
email = "Estillman13@gmail.com"
facebook = ""
github = ""
googleplus = ""
instagram = ""
linkedin = ""
pinterest = ""
rss = false
stackoverflow = ""
twitter = "@EliStillman13"
